cognitive-complexity-threshold = 30
too-many-arguments-threshold = 10
type-complexity-threshold = 500
single-char-binding-names-threshold = 4
too-large-for-stack = 200
enum-variant-name-threshold = 3
literal-representation-threshold = 10
