pub const SINGLE_MESSAGE_MODE: i32 = 0;
pub const ACCIDENTAL_MODE: i32 = 1;
pub const MOBILE_MODE: i32 = 2;
pub const BROADCAST_MODE: i32 = 3;

pub const POLARIZATION_HORIZONTAL: i32 = 0;
pub const POLARIZATION_VERTICAL: i32 = 1;

pub const SITING_CRITERIA_RANDOM: i32 = 0;
pub const SITING_CRITERIA_CAREFUL: i32 = 1;
pub const SITING_CRITERIA_VERY_CAREFUL: i32 = 2;

pub const CLIMATE_EQUATORIAL: i32 = 1;
pub const CLIMATE_CONTINENTAL_SUBTROPICAL: i32 = 2;
pub const CLIMATE_MARITIME_SUBTROPICAL: i32 = 3;
pub const CLIMATE_DESERT: i32 = 4;
pub const CLIMATE_CONTINENTAL_TEMPERATE: i32 = 5;
pub const CLIMATE_MARITIME_TEMPERATE_OVER_LAND: i32 = 6;
pub const CLIMATE_MARITIME_TEMPERATE_OVER_SEA: i32 = 7;

pub const MODE_NOT_SET: i32 = 0;
pub const MODE_LINE_OF_SIGHT: i32 = 1;
pub const MODE_DIFFRACTION: i32 = 2;
pub const MODE_TROPOSCATTER: i32 = 3;

pub const MDVAR_SINGLE_MESSAGE_MODE: i32 = 0;
pub const MDVAR_ACCIDENTAL_MODE: i32 = 1;
pub const MDVAR_MOBILE_MODE: i32 = 2;
pub const MDVAR_BROADCAST_MODE: i32 = 3;
